name: jamiemeinecke
favicon: null
layout_spectrum: 0.51057
typography_spectrum: 0.59232
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010207'
    - '#809ea5'
    - '#ccccca'
    - '#55707b'
    - '#2d5665'
  brandStrength: 0.125
  lightness: 0.49495298136025667
  saturation: 0.9461304135620594
  rhythmicContrast: 0.7016819277778268
purpose: []
